In [10]:
import filterpy.common
import numpy as np
dt = 0.01
processNoise = 1e-4 
b=np.eye(3) 

In [11]:
a=np.array(filterpy.common.Q_discrete_white_noise(dim=3, dt=dt, var=processNoise))

In [12]:
a*b

array([[2.5e-13, 0.0e+00, 0.0e+00],
       [0.0e+00, 1.0e-08, 0.0e+00],
       [0.0e+00, 0.0e+00, 1.0e-04]])

In [13]:
np.eye(3,b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [18]:
np.array([[b+0*b],
 [0*b+b]])

array([[[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]],


       [[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]]])

In [25]:
np.kron(np.eye(3),filterpy.common.Q_discrete_white_noise(dim=3,dt=dt,var=processNoise))

array([[2.5e-13, 5.0e-11, 5.0e-09, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [5.0e-11, 1.0e-08, 1.0e-06, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [5.0e-09, 1.0e-06, 1.0e-04, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 2.5e-13, 5.0e-11, 5.0e-09, 0.0e+00,
        0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 5.0e-11, 1.0e-08, 1.0e-06, 0.0e+00,
        0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 5.0e-09, 1.0e-06, 1.0e-04, 0.0e+00,
        0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 2.5e-13,
        5.0e-11, 5.0e-09],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 5.0e-11,
        1.0e-08, 1.0e-06],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 5.0e-09,
        1.0e-06, 1.0e-04]])

In [24]:
b

array([[2.5e-13, 5.0e-11, 5.0e-09, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [5.0e-11, 1.0e-08, 1.0e-06, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [5.0e-09, 1.0e-06, 1.0e-04, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 2.5e-13, 5.0e-11, 5.0e-09, 0.0e+00,
        0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 5.0e-11, 1.0e-08, 1.0e-06, 0.0e+00,
        0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 5.0e-09, 1.0e-06, 1.0e-04, 0.0e+00,
        0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 2.5e-13,
        5.0e-11, 5.0e-09],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 5.0e-11,
        1.0e-08, 1.0e-06],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 5.0e-09,
        1.0e-06, 1.0e-04]])